server:
  port: 8081
  servlet:
    context-path: /service-auth

spring:
  redis:
    host: localhost
    port: 6379
    database: 0
  datasource:
    service-auth:
      jdbc-url: jdbc:mysql://localhost:3306/auth?useSSL=false&zeroDateTimeBehavior=convertToNull&allowMultiQueries=true
      username: dpc
      password: dpc123
      driver-class-name: com.mysql.jdbc.Driver
